Add Acl plugin to the Readme
aurora-is-near/near-plugins pull request #42
Opened 2022-11-23 13:49 UTC by mooori

An introduction of the Acl plugin was missing - it was still listed unter Roadmap.

2022-11-23 16:34 UTC, sept-en requested changes

2022-11-23 16:34 UTC, sept-en commented on README.md
> +Enables role based access control for contract methods. A method with restricted access can only be called _successfully_ by accounts that have been granted one of the whitelisted roles. If a restric
```suggestion
Enables role-based access control for contract methods. A method with restricted access can only be called _successfully_ by accounts that have been granted one of the whitelisted roles. If a restricted method is called by an account with insufficient permissions, it panics.
```

2022-11-23 16:34 UTC, sept-en commented on README.md
> +        );
I think it's worth adding variables for `admin_account_id` and `grantee_account_id` just to show that these are user-defined.

E.g.:
```rust
// Define the account you would like to be an admin
let skipper_by_one_admin_account_id: AccountId = "alice.near".parse().unwrap();
```

It's also worth adding a comment for the "add an admin" part that we are adding an admin just for the specific role. Even though it's mentioned before that admins and super-admins are different in the ACL hierarchy, I don't think the comment would be redundant.

2022-11-23 16:34 UTC, sept-en commented on README.md
> +    /// successfully call this method.
There's also a third role that exists, so "any of the whitelisted roles" could be confusing. It's better to explain roles for the example explicitly.
```suggestion
    /// Only an account that was granted either `SkipperByOne` or `SkipperByAny` roles may
    /// successfully call this method.
```

2022-11-23 19:09 UTC, mooori commented
@sept-en I've marked above comments as resolved since they were adressed in be31e02.

2022-11-24 02:01 UTC, sept-en approved these changes

2022-11-24 02:01 UTC, sept-en commented on README.md
> +        // Specify an account to be added as admin for a specifc role.
A small typo
```suggestion
        // Specify an account to be added as admin for a specific role.
```

2022-11-25 10:20 UTC, mfornet approved these changes

2022-11-25 10:21 UTC, mfornet commented
@mooori I missed your comment in #43 and merged it. Can you please fix conflicting files here and merge?

2022-11-25 16:24 UTC, merged